### ISSUE TITLE
Validation Requests

### ISSUE THREAD

**Issue by goguma-chsong** [KAIST-IS521/2019s-gitctf-3rdparty#5]
[team3_bug3.zip.asc.txt](https://github.com/KAIST-IS521/2019s-gitctf-3rdparty/files/3153684/team3_bug3.zip.asc.txt)

**Comment by dohki** [comment]
I cannot decrypt.

**Comment by dohki** [comment]
and Do not leak the info that bug exists

**Comment by dinggul** [comment]
Use this file instead of above one @dohki 
[team2to3.zip.asc.txt](https://github.com/KAIST-IS521/2019s-gitctf-3rdparty/files/3155620/team2to3.zip.asc.txt)
